WEBSITES_PATH = "/Volumes/Untitled/R/Thesis/websites.csv"
STATES_PATH = "/Volumes/Untitled/R/Thesis/states.csv"
COLORS_PATH = "/Volumes/Untitled/R/Thesis/blue-red.csv"
OLD_DATA_PATH = "/Volumes/Untitled/R/Thesis/DATA"
NEW_DATA_PATH = "/Volumes/Untitled/R/Thesis/NEW_DATA"
DATA_PATH = "/Volumes/Untitled/R/Thesis/DATA"
NAMES_PATH = "/Volumes/Untitled/R/Thesis/new_names.csv"
